coverage_service: cobertura_xml
workspace: ReactiveDataDisplayManagerExample.xcworspace
xcodeproj: ReactiveDataDisplayManagerExample.xcodeproj
scheme: ReactiveDataDisplayManagerExample_iOS
source_directory: ReactiveDataDisplayManager
output_directory: build/reports
