use_frameworks!

target 'ReactiveDataDisplayManagerExample_iOS' do
  pod 'ReactiveDataDisplayManager', :path => '../'
  pod 'SurfUtils/ItemsScrollManager', :git => "https://github.com/surfstudio/iOS-Utils.git", :tag => '11.0.0'
  pod 'Nuke', :git => "https://github.com/kean/Nuke.git", :tag => '9.5.1'
  pod 'DifferenceKit', '1.1.5'
  target 'ReactiveDataDisplayManagerExample_iOS_M1' do
  end
  target 'ReactiveDataDisplayManagerExampleUITests' do
  end
  target 'ReactiveDataDisplayManagerExampleUITests_M1' do
  end
end

target 'ReactiveDataDisplayManagerExample_tvOS' do
  pod 'ReactiveDataDisplayManager', :path => '../'
  pod 'Nuke', :git => "https://github.com/kean/Nuke.git", :tag => '9.5.1'
end
