
include:
  - path: targets/testTemplate.yml
    relativePaths: false
  - path: targets/example_iOS_Template.yml
    relativePaths: false
  - path: targets/example_tvOS_Template.yml
    relativePaths: false

# Название проекта
name: ReactiveDataDisplayManagerExample
options:
  # Версия Xcode
  xcodeVersion: 13.3
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
settings:
  DEVELOPMENT_TEAM: EFAAG9GXN4
targets:
    ReactiveDataDisplayManagerExample_iOS:
      templates:
        - ReactiveDataDisplayManagerExample_iOS_Template
      scheme:
        configVariants: all
        testTargets:
          - ReactiveDataDisplayManagerExampleUITests

    ReactiveDataDisplayManagerExample_iOS_M1:
      templates:
        - ReactiveDataDisplayManagerExample_iOS_Template
      scheme:
        configVariants: all
        testTargets:
          - ReactiveDataDisplayManagerExampleUITests_M1

    ReactiveDataDisplayManagerExample_tvOS:
        templates:
          - ReactiveDataDisplayManagerExample_tvOSTemplate
        configs:
          Debug:
            EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"

    ReactiveDataDisplayManagerExampleUITests:
        templates:
          - ReactiveDataDisplayManagerExampleUITestsTemplate
        dependencies:
          - target: ReactiveDataDisplayManagerExample_iOS
        settings:
          configs:
            Debug:
              EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"
              TEST_TARGET_NAME: ReactiveDataDisplayManagerExample_iOS

    ReactiveDataDisplayManagerExampleUITests_M1:
        templates:
          - ReactiveDataDisplayManagerExampleUITestsTemplate
        dependencies:
          - target: ReactiveDataDisplayManagerExample_iOS_M1
        settings:
          configs:
            Debug:
              TEST_TARGET_NAME: ReactiveDataDisplayManagerExample_iOS

