
include:
  - path: targets/template.yml
    relativePaths: true


# Название проекта
name: ReactiveDataDisplayManagerExample
options:
  # Версия Xcode
  xcodeVersion: 13.4.1
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
settings:
  DEVELOPMENT_TEAM: EFAAG9GXN4

packages:
  Vapor:
    github: vapor/vapor
    from: 4.0.0

targets:

    ReactiveServer_macOS:
      type: tool
      platform: macOS
      deploymentTarget: 12.0
      sources: ReactiveServer/Sources
      dependencies:
        - package: Vapor

    ReactiveChat_iOS:
      platform: iOS
      deploymentTarget: 13.0
      sources:
        - path: ReactiveChat
        - path: ReactiveServer/Sources/Model
      dependencies:
        - target: ReactiveDataDisplayManager_iOS
        - target: ReactiveDataComponents_iOS
      info:
        path: ReactiveChat/Application/Info.plist
      templates:
        - BaseApp
        - BaseSettings
      templateAttributes:
        bundle_id: ru.surfstudio.rddm.chat
        bundle_name: ReactiveChatExample

    ReactiveDataDisplayManagerExample_iOS:
      platform: iOS
      deploymentTarget: 11.0
      scheme:
          configVariants: all
          testTargets:
            - ReactiveDataDisplayManagerExampleUITests
          gatherCoverageData: true
      sources:
        - path: ReactiveDataDisplayManager
      dependencies:
        - target: ReactiveDataDisplayManager_iOS
        - target: ReactiveDataComponents_iOS
      info:
        path: ReactiveDataDisplayManager/Application/Info.plist
      templates:
        - BaseApp
        - BaseSettings
      templateAttributes:
        bundle_id: ru.surfstudio.rddm.example
        bundle_name: ReactiveDataDisplayManagerExample

    ReactiveDataDisplayManagerExample_tvOS:
      platform: tvOS
      deploymentTarget: 13.0
      sources:
        - path: ReactiveDataDisplayManagerExampleTv
      dependencies:
        - target: ReactiveDataDisplayManager_tvOS
        - target: ReactiveDataComponents_tvOS
      info:
        path: ReactiveDataDisplayManagerExampleTv/Application/Info.plist
      templates:
        - BaseApp
        - BaseSettings
      templateAttributes:
        bundle_id: ru.surfstudio.rddm.tv_example
        bundle_name: ReactiveDataDisplayManagerExampleTv

    ReactiveDataDisplayManagerExampleUITests:
        templates:
          - BaseUITest
          - BaseSettings
        templateAttributes:
          bundle_id: ru.surfstudio.rddm.tv_example.tests
        dependencies:
          - target: ReactiveDataDisplayManagerExample_iOS
        sources: [ReactiveDataDisplayManagerExampleUITests]
        info:
          path: ReactiveDataDisplayManagerExampleUITests/Info.plist
          properties: []
        settings:
          configs:
            Debug:
              TEST_TARGET_NAME: ReactiveDataDisplayManagerExample_iOS
