
include:
  - path: targets/template.yml
    relativePaths: false


# Название проекта
name: ReactiveDataDisplayManagerExample
options:
  # Версия Xcode
  xcodeVersion: 13.3
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
settings:
  DEVELOPMENT_TEAM: EFAAG9GXN4
targets:

    ReactiveDataDisplayManagerExample_iOS:
      platform: iOS
      deploymentTarget: 11.0
      sources:
        - path: ReactiveDataDisplayManager
      dependencies:
        - target: ReactiveDataDisplayManager_iOS
      info:
        path: ReactiveDataDisplayManager/Application/Info.plist
      templates:
        - BaseSetting
      templateAttributes:
        bundle_name: ReactiveDataDisplayManagerExample
        ui_test: ReactiveDataDisplayManagerExampleUITests

    ReactiveDataDisplayManagerExample_tvOS:
      platform: tvOS
      deploymentTarget: 13.0
      sources:
        - path: ReactiveDataDisplayManagerExampleTv
      dependencies:
        - target: ReactiveDataDisplayManager_tvOS
      info:
        path: ReactiveDataDisplayManagerExampleTv/Application/Info.plist
      templates:
        - BaseSetting
      templateAttributes:
        bundle_name: ReactiveDataDisplayManagerExampleTv
        ui_test: ReactiveDataDisplayManagerExampleUITests
      configs:
        Debug:


    ReactiveDataDisplayManagerExampleUITests:
        templates:
          - ReactiveDataDisplayManagerExampleUITestsTemplate
        dependencies:
          - target: ReactiveDataDisplayManagerExample_iOS
        settings:
          configs:
            Debug:

              TEST_TARGET_NAME: ReactiveDataDisplayManagerExample_iOS


# Шаблон для тестовых таргетов
targetTemplates:
    ReactiveDataDisplayManagerExampleUITestsTemplate:
        type: bundle.ui-testing
        platform: iOS
        deploymentTarget:
          iOS: 10.0
          tvOS: 10.0
        scheme:
          configVariants: all
          gatherCoverageData: true
        sources: [ReactiveDataDisplayManagerExampleUITests]
        info:
          path: ReactiveDataDisplayManagerExampleUITests/Info.plist
          properties: []
