coverage_service: cobertura_xml
workspace: ReactiveDataDisplayManager.xcworkspace
xcodeproj: ReactiveDataDisplayManager.xcodeproj
scheme: ReactiveDataDisplayManager_iOS
source_directory: Source
output_directory: build/reports
