include:
  - path: Example/project.yml
    relativePaths: true

# Название проекта
name: ReactiveDataDisplayManager
options:
  # Версия Xcode
  xcodeVersion: 13.3
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
targets:
    ReactiveDataDisplayManager:
      dependencies:
        - sdk: UIKit.framework
      type: framework
      platform: [iOS, tvOS]
      deploymentTarget:
        iOS: 10.0
        tvOS: 10.0
      scheme:
        configVariants: all
        testTargets:
          - ReactiveDataDisplayManagerTests_${platform}
        gatherCoverageData: true
      sources:
        - path: Source
      info:
        path: Info.plist
        properties:
          CFBundleName: ReactiveDataDisplayManager
          CFBundleShortVersionString: $(MARKETING_VERSION)
          CFBundleVersion: $(CURRENT_PROJECT_VERSION)
      settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: ru.surfstudio.rddm
          MARKETING_VERSION: "7.2.1"
          CURRENT_PROJECT_VERSION: 0
          VERSIONING_SYSTEM: "apple-generic"
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
          CODE_SIGN_IDENTITY: None
          CODE_SIGN_STYLE: Manual


    ReactiveDataDisplayManagerTests:
      type: bundle.unit-test
      platform: [iOS, tvOS]
      deploymentTarget:
        iOS: 10.0
        tvOS: 10.0
      scheme:
        configVariants: all
      sources: [ReactiveDataDisplayManagerTests]
      info:
        path: ReactiveDataDisplayManagerTests/Info.plist
        properties: []
      dependencies:
        - target: ReactiveDataDisplayManager_${platform}
      preBuildScripts:
        - script: sourcery
          name: Sourcery
      settings:
        base:
          CODE_SIGN_IDENTITY: None
          CODE_SIGN_STYLE: Manual
