# Название проекта
name: ReactiveDataComponents
options:
  # Версия Xcode
  xcodeVersion: 13.4.1
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
targets:
    ReactiveDataComponents:
      dependencies:
        - sdk: UIKit.framework
      type: framework
      platform: [iOS, tvOS]
      deploymentTarget:
        iOS: 10.0
        tvOS: 10.0
      scheme:
        configVariants: all
        testTargets:
          - ReactiveDataComponentsTests_${platform}
        gatherCoverageData: true
      sources:
        - path: Source
      dependencies:
        - target: ReactiveDataDisplayManager_${platform}
      info:
        path: Info.plist
        properties:
          CFBundleName: ReactiveDataComponents
          CFBundleShortVersionString: $(MARKETING_VERSION)
          CFBundleVersion: $(CURRENT_PROJECT_VERSION)
      settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: ru.surfstudio.rddm.components
          MARKETING_VERSION: "8.0.0"
          CURRENT_PROJECT_VERSION: 0
          VERSIONING_SYSTEM: "apple-generic"
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
          CODE_SIGN_IDENTITY: None
          CODE_SIGN_STYLE: Manual


    ReactiveDataComponentsTests:
      type: bundle.unit-test
      platform: [iOS, tvOS]
      deploymentTarget:
        iOS: 10.0
        tvOS: 10.0
      scheme:
        configVariants: all
      sources: [Tests]
      info:
        path: ReactiveDataComponentsTests/Info.plist
        properties: []
      dependencies:
        - target: ReactiveDataComponents_${platform}
      preBuildScripts:
        - script: sourcery
          name: Sourcery
      settings:
        base:
          CODE_SIGN_IDENTITY: None
          CODE_SIGN_STYLE: Manual
