//
//  BaseCollectionCellGenerator.swift
//  ReactiveDataDisplayManager
//
//  Created by Maxim MAMEDOV on 28/03/2019.
//  Copyright © 2019 Александр Кравченков. All rights reserved.
//

import UIKit

open class BaseCollectionCellGenerator<Cell: ConfigurableItem>: SelectableItem where Cell: UICollectionViewCell {

    // MARK: - Public Properties

    public var isNeedDeselect = true
    public var didSelectEvent = EmptyEvent()
    public var didDeselectEvent = EmptyEvent()
    public let model: Cell.Model

    // MARK: - Private Properties

    private let registerType: RegistrationType

    // MARK: - Initialization

    public init(with model: Cell.Model,
                registerType: RegistrationType = .nib) {
        self.model = model
        self.registerType = registerType
    }

    // MARK: - Open methods

    open func configure(cell: Cell, with model: Cell.Model) {
        cell.configure(with: model)
    }

}

// MARK: - CollectionCellGenerator

extension BaseCollectionCellGenerator: CollectionCellGenerator {

    public var identifier: String {
        return String(describing: Cell.self)
    }

    public func generate(collectionView: UICollectionView, for indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: identifier, for: indexPath) as? Cell else {
            return UICollectionViewCell()
        }
        configure(cell: cell, with: model)
        return cell
    }

    public func registerCell(in collectionView: UICollectionView) {
        switch registerType {
        case .nib:
            collectionView.registerNib(identifier, bundle: Cell.bundle())
        case .class:
            collectionView.register(Cell.self, forCellWithReuseIdentifier: identifier)
        }
    }

}

// MARK: - Decorations

public extension BaseCollectionCellGenerator {

    /// - Parameter isNeedDeselect: defines if cell should be deselected after selection
    func isNeedDeselect(_ isNeedDeselect: Bool) -> Self {
        self.isNeedDeselect = isNeedDeselect
        return self
    }

    /// - Parameter closure: closure that will be called when cell is selected
    func didSelectEvent(_ closure: @escaping () -> Void) -> Self {
        self.didSelectEvent.addListner(closure)
        return self
    }

    /// - Parameter closure: closure that will be called when cell is deselected in multiple selection mode
    func didDeselectEvent(_ closure: @escaping () -> Void) -> Self {
        self.didDeselectEvent.addListner(closure)
        return self
    }

}

// MARK: - Transformations

public extension BaseCollectionCellGenerator where Cell: FoldableStateHolder {

    /// Creates FoldableCellGenerator with predefined children
    /// - Parameter children: array of children
    func asFoldable(_ children: [CollectionCellGenerator]) -> FoldableCollectionCellGenerator<Cell> {
        return .init(with: model,
                     registerType: registerType)
            .children(children)
    }

    /// Creates FoldableCellGenerator with children generated by resultBuilder
    /// - Parameter content: resultBuilder based closure that returns array of children
    func asFoldable(@GeneratorsBuilder<CollectionCellGenerator>_ content: @escaping (CollectionContext.Type) -> [CollectionCellGenerator]) -> FoldableCollectionCellGenerator<Cell> {
        return .init(with: model,
                     registerType: registerType)
            .children(content)
    }

}

public extension BaseCollectionCellGenerator where Cell.Model: Equatable {

    /// Creates DiffableCellGenerator with constant but unique Id
    ///  - Parameter uniqueId: uniqueId to identify cell
    func asDiffable(uniqueId: AnyHashable) -> DiffableCollectionCellGenerator<Cell> {
        .init(uniqueId: uniqueId,
              with: model,
              registerType: registerType)
    }

}

public extension BaseCollectionCellGenerator where Cell.Model: Equatable & IdOwner {

    /// Creates DiffableCellGenerator with uniqueId from model
    func asDiffable() -> DiffableCollectionCellGenerator<Cell> {
        .init(uniqueId: model.id,
              with: model,
              registerType: registerType)
    }

}
