name: Build

on:
  push:
    branches:
      - develop
      - preview/version-8
  pull_request:

jobs:

  build_iOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build
      run: make build_lib_iOS
    - name: Run tests
      run: make test_lib_iOS
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash) -J 'ReactiveDataDisplayManager'

  build_Example:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Run tests
      run: make test_example_iOS

  build_tvOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build
      run: make build_lib_tvOS
