name: Build

on:
  push:
    branches:
      - develop
      - preview/version-8
  pull_request:

jobs:

  build_iOS:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build
      run: make build_lib_iOS
    - name: Run tests
      run: make test_lib_iOS
    - name: Check Log
      run: make check_test_log
    - name: Prepare Report
      run: make prepare_report
    - name: Upload Coverage
      uses: codecov/codecov-action@v3.1.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: build/reports/cobertura.xml
        flags: unittests
        name: codecov-unit
        xcode: true
        fail_ci_if_error: true
        verbose: true


  build_Example:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build
      run: make build_example_iOS
    - name: Run tests
      run: make test_example_iOS
    - name: Check Log
      run: make check_test_log
    - name: Prepare Report
      run: make prepare_example_report
    - name: Upload Coverage
      uses: codecov/codecov-action@v3.1.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: build/reports/cobertura.xml
        flags: uitests
        name: codecov-ui
        xcode: true
        fail_ci_if_error: true
        verbose: true

  build_tvOS:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build lib
      run: make build_lib_tvOS
    - name: Build example
      run: make build_example_tvOS

  build_SPM:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build_example_SPM version=15.5
