name: Build

on:
  push:
    branches:
      - develop
      - preview/version-8
  pull_request:

jobs:

  build_iOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build
      run: make build_lib_iOS
    - name: Run tests
      run: make test_lib_iOS
    - name: Upload Coverage
      uses: codecov/codecov-action@v3.1.0
      with:
        flags: unittests
        name: codecov-unit
        xcode: true
        fail_ci_if_error: true
        verbose: true


  build_Example:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build
      run: make build_example_iOS
    - name: Run tests
      run: make test_example_iOS
    - name: Upload Coverage
      uses: codecov/codecov-action@v3.1.0
      with:
        flags: uitests
        name: codecov-ui
        xcode: true
        fail_ci_if_error: true
        verbose: true

  build_tvOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate projects
      run: make init
    - name: Build
      run: make build_lib_tvOS
