name: Jira

on:
  pull_request:
    # пока для тестов будет запускаться для всех ивентов
    # types: [opened, reopened, closed]

jobs:
  update-jira-board:
    name: "Update Jira Board"
    runs-on: ubuntu-latest
    steps:
    - name: Get tasks tokens
      id: tasks_tokens
      run: |
        tokens=$(echo ${{ github.event.pull_request.title }} | grep -E -o "SPT-[0-9]{1,}")
        echo "tokens=${tokens}" >> $GITHUB_OUTPUT
        echo "Obtained next tokens:\n $tokens"
    - name: Update tasks on Jira board
      run: |
        for token in ${{ steps.tasks_tokens.outputs.tokens }}; do
          echo "task: $token"
        done
        echo "PR is merged: ${{ github.event.pull_request.merged }}"
  
  
